### ISSUE TITLE
Assert response not called/fired?

### ISSUE THREAD

**Issue by pawamoy** [Colin-b/pytest_httpx#18]
Some functions I'm testing are caching results. I'd like to assert that subsequent calls **do not** hit the network.

I'm thinking of something like this:

```python
def test_cached_results(httpx_mock):
    response = httpx_mock.add_response()
    my_function(...)
    
    # in two statements:
    assert not response.fired
    httpx_mock.remove(response)

    # in one statement: pop and assert not fired
    assert not httpx_mock.pop().fired

    # one statement, variant: if the response exists, it is removed, otherwise it fails
    assert httpx_mock.remove(response)
```

**Comment by pawamoy** [comment]
Oh I see I can this:

```python
assert not httpx_mock.get_requests()
```

**Comment by Colin-b** [comment]
yes, in your case if you expect your function to send a single httpx request, then you can assert the len of the requests that were sent (I find it better to check the content of what was actually sent but that is up to you).

If your code is supposed to send one query and cache the result so that you don't send anymore queries, then you can use

```python
def test_cached_results(httpx_mock):
    httpx_mock.add_response()
    my_function(...)

   assert 1 == len(httpx_mock.get_requests())
```

**Comment by pawamoy** [comment]
Oh I thougt `get_requests` was returning the request that were actually sent on the network, but actually it makes sense that it's not the case 🙂 

Thank you @Colin-b, this solves my use-case, feel free to close 🙂
